name: Build and publish python package

on:
  workflow_call:
    inputs:
      python_version:
        default: '3.11'
        description: 'Python version to use'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      python_version:
        default: '3.11'
        description: 'Python version to use'
        required: true
        type: string

permissions: {}

jobs:
  build-and-publish-package:
    environment: release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout arelle
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v4.6.1
        with:
          cache: 'pip'
          check-latest: true
          python-version: ${{ inputs.python_version }}
      - name: Build python package
        run: |
          python -m pip install --upgrade pip setuptools twine wheel
          pip install build
          python -m build
      - name: Upload tar artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: arelle.tar.gz
          if-no-files-found: error
          path: dist/*.tar.gz
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: arelle.whl
          if-no-files-found: error
          path: dist/*.whl
      - name: Publish package on release
        if: startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          TWINE_REPOSITORY: ${{ github.repository == 'Arelle/Arelle' && 'pypi' || 'testpypi' }}
        run: twine upload dist/*
      - name: Upload release artifact
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v0.1.15
        with:
          fail_on_unmatched_files: true
          files: 'dist/*'
